# Generated by Django 5.0.1 on 2024-01-26 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieBack', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='image',
        ),
    ]
