# Generated by Django 5.0.1 on 2024-01-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieBack', '0002_remove_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.TextField(default=''),
        ),
    ]
